(()=>{
const q=s=>document.querySelector(s),safe=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const valid=v=>typeof v==='number'&&Number.isFinite(v),p=(v,d=1)=>valid(v)?(v>0?'+':'')+(v*100).toFixed(d)+'%':'—',ratio=v=>valid(v)?(v*100).toFixed(1)+'%':'—',tone=v=>valid(v)?v<0?'env-negative':v>0?'env-positive':'':'';
let db,idx=0,pressureMetric='down5',feedbackMetric='intraday',refreshBusy=false;
const expanded=new Set();
const getters={mean:r=>r.breadth_rebuilt?.mean??r.mean_return,median:r=>r.breadth_rebuilt?.median??r.median_return,down5:r=>r.breadth_rebuilt?r.breadth_rebuilt.down5/r.breadth_rebuilt.count:null,down7:r=>r.breadth_rebuilt?r.breadth_rebuilt.down7/r.breadth_rebuilt.count:null,limit:r=>r.limit_down_count,down:r=>r.breadth_rebuilt?r.breadth_rebuilt.down/r.breadth_rebuilt.count:null};
function rank(rows,index,get,lower=false){const now=get(rows[index]),sample=rows.slice(Math.max(0,index-250),index).map(get).filter(valid);if(!valid(now)||!sample.length)return {n:sample.length,value:null};let v=(sample.filter(x=>x<now).length+sample.filter(x=>x===now).length*.5)/sample.length*100;return {n:sample.length,value:lower?100-v:v}}
function rememberExpanded(){q('#env-cards').querySelectorAll('details[data-fold]').forEach(el=>{if(el.open)expanded.add(el.dataset.fold);else expanded.delete(el.dataset.fold)})}
function fold(key,title,body){return `<details class="env-details" data-fold="${key}" ${expanded.has(key)?'open':''}><summary>${title}</summary>${body}</details>`}
const stat=(label,v,n,expected,definition='')=>`<div class="env-stat" title="${safe(definition)}"><span>${label}</span><b class="${tone(v)}">${p(v,2)}</b>${n<expected?`<small>有效 ${n}/${expected}只</small>`:!n?'<small>无有效样本</small>':''}</div>`;
function details(key,title,items,liveMode=false){if(!items.length)return fold(key,title+' · 无样本','<p class="env-muted">无符合条件的样本。</p>');const close=liveMode?'当前':'今收';return fold(key,`${title} · ${items.length}只`,`<div class="env-scroll"><table><thead><tr><th>样本</th><th>前日高度</th><th>昨收→今开</th><th>今开→${close}</th><th>昨收→${close}</th></tr></thead><tbody>${items.map(s=>`<tr><td>${safe(s.name)}<small>${safe(s.code)}</small></td><td>${s.height}板</td><td class="${tone(s.gap)}">${p(s.gap,2)}</td><td class="${tone(s.intraday)}">${p(s.intraday,2)}</td><td class="${tone(s.total)}">${p(s.total,2)}</td></tr>`).join('')}</tbody></table></div>`)}
function card(title,badge,body,bad=false){return `<article class="env-card"><div class="env-card-head"><h3>${title}</h3><span class="env-pill ${bad?'bad':''}">${badge}</span></div><div class="env-card-body">${body}</div></article>`}
function limitDownDetails(row){const source=row.limit_down_source,stocks=row.limit_down_stocks;if(!source||!Array.isArray(stocks))return '';const check=source.quote_check,validation=check?.status==='matched'?`普通主板10%股票与独立行情逐只核对一致（${check.quote_count}只）。`:check?'两路行情采样有差异，等待核对。':safe(source.history_check||'未完成逐股跨源核对')+'。';return fold('limit-stocks',`跌停明细 · ${stocks.length}只`,`<p class="env-muted">${safe(source.name)}：${safe(source.definition)}。${validation}</p>${stocks.length?`<div class="env-scroll"><table><thead><tr><th>股票</th><th>涨跌幅</th></tr></thead><tbody>${stocks.map(s=>`<tr><td>${safe(s.name)}<small>${safe(s.code)}</small></td><td class="env-negative">${p(s.return,2)}</td></tr>`).join('')}</tbody></table></div>`:'<p>已确认该日仍在留存期，跌停池总数与明细均为0。</p>'}`)}
function chart(points,label,count=false){const present=points.filter(x=>valid(x.v));if(present.length<2)return '<div class="env-empty">有效样本不足，暂不绘制走势。</div>';const lo=Math.min(0,...present.map(x=>x.v)),hi=Math.max(0,...present.map(x=>x.v)),y=v=>116-(v-lo)/(hi-lo||1)*94;const x=i=>48+i/Math.max(1,points.length-1)*460;let segments=[],part=[];points.forEach((a,i)=>{if(valid(a.v))part.push(`${x(i)},${y(a.v)}`);else if(part.length){segments.push(part.join(' '));part=[]}});if(part.length)segments.push(part.join(' '));return `<svg class="env-linechart" viewBox="0 0 530 150" role="img" aria-label="${safe(label)}"><line x1="48" x2="508" y1="${y(0)}" y2="${y(0)}" stroke="#45536b" stroke-dasharray="4 4"/><text class="env-chart-label" x="0" y="26">${count?Math.round(hi):ratio(hi)}</text><text class="env-chart-label" x="0" y="118">${count?Math.round(lo):ratio(lo)}</text>${segments.map(s=>`<polyline points="${s}" fill="none" stroke="#85baff" stroke-width="2.5"/>`).join('')}${points.map((a,i)=>valid(a.v)?`<circle cx="${x(i)}" cy="${y(a.v)}" r="3" fill="#ffca77"><title>${a.date}：${count?a.v+'只':p(a.v,2)}</title></circle>`:'').join('')}<text class="env-chart-label" x="48" y="142">${points[0].date.slice(5)}</text><text class="env-chart-label" x="465" y="142">${points.at(-1).date.slice(5)}</text></svg>`}

function render(){
rememberExpanded();
const report=db.reports[idx],rows=db.market.rows.filter(r=>r.date<=report.date),i=rows.length-1,m=rows[i],mp=rows[i-1],relay=report.relay,failure=report.failure,hf=report.high_follow_stats;
payload={...db.market,rows};renderKpis(rows);renderTable(rows);renderChart(rows);renderRelayMatrix(rows);updateTemperatureExplanation(rows);if(!dom.temperatureModal.hidden)renderTemperatureChart(rows);if(!dom.phaseModal.hidden)renderPhaseChart(rows);if(!dom.metricModal.hidden)renderMetricChart(rows);
const current=report.date===db.asof,liveMode=current&&!db.final;
const cohortN=report.cohort?.length||0,failureN=failure.total.n;
dom.phaseCard.title+=` · ${liveMode?'暂未封板':'断板'}有效${failureN}/${cohortN}只，中位数${p(failure.total.median,2)}，跌幅≥7%占比${ratio(failure.total.severe)}`;
if(liveMode){dom.phase.textContent+='（盘中）';dom.temperatureSub.innerHTML=dom.temperatureSub.innerHTML.replaceAll('断板','暂未封板');}
q('#env-context').textContent=`${report.date} ${current?(db.quote_time||'15:00:00'):'收盘'} · ${liveMode?'盘中快照':'收盘数据'}`;
dom.updateTime.textContent='最近成功更新 '+(db.fetched_at||db.market.updated_at).replace('T',' ').slice(0,19);dom.reloadBtn.textContent='立即更新';
q('#coverage-detail').innerHTML=`<p>全市场有效报价 ${db.coverage?.market_stocks??'—'}/${db.coverage?.listed_stocks??'—'}只；历史日线 ${db.coverage?.history_received??'—'}/${db.coverage?.history_expected??'—'}只；广度记录 ${db.coverage?.breadth_days??'—'}日；接力反馈 ${db.coverage?.feedback_days??db.reports.length}日。失败行情项 ${db.coverage?.feedback_errors?.length??0}项。历史名单不含已经退市的股票。</p>`;
q('#coverage-detail').innerHTML+=`<p>来源审查：已重取 ${db.audit?.limit_down_verified_days??'—'} 日历史跌停汇总核对；最近 ${db.audit?.recent_detail_days??'—'} 日留有跌停明细。历史原始值、修订差异均已保存。</p><div class="env-scroll"><table class="env-source-table"><thead><tr><th>指标</th><th>来源与范围</th></tr></thead><tbody>${[['广度、中位数、大跌占比',m.breadth_source||'历史公开汇总；回建范围见下方说明'],['涨停 / 跌停','非ST收盘封板；近期东方财富池，早期开盘红SJZT/SJDT字段。盘中为当前封板。'],['历史表中的涨停反馈',m.feedback_scope||'非ST各板块均值，含20%股票；昨涨停未封板包含昨日首板'],['接力结构与风险中的连板反馈','非ST 10%主板昨日二板及以上；收益以中位数显示。前日固定名单包含失败者。'],['成交额',m.turnover_source||'历史公开汇总，范围未完整留存']].map(([name,scope])=>`<tr><td>${name}</td><td>${safe(scope)}</td></tr>`).join('')}</tbody></table></div><p>上方市场广度为上涨÷（上涨＋下跌），不含平盘；下方大跌、下跌占比按全部有效报价计算，含平盘。两处使用同一组涨跌家数。早期“连板率”由当日连板数÷昨日涨停数近似，不能等同逐股晋级率；旧成交额跨来源比较仅供参考。</p>`;

const metrics=[['平均涨跌幅','mean',true],['涨跌中位数','median',true],['跌幅≥5%占比','down5',false],['跌幅≥7%占比','down7',false],['跌停数量','limit',false],['下跌占比','down',false]];
const pressureRows=metrics.map(([name,key,lower])=>{
 const v=getters[key](m),prior=mp?getters[key](mp):null,r=rank(rows,i,getters[key],lower),diff=valid(v)&&valid(prior)?(v-prior)*(key==='limit'?1:100):null;
 const count=key==='down5'?m.breadth_rebuilt?.down5:key==='down7'?m.breadth_rebuilt?.down7:key==='down'?m.breadth_rebuilt?.down:null;
 const hint=key==='limit'?'非ST封住跌停':valid(count)?count+'只':'';
 const rankReady=valid(r.value)&&r.n>=200,rankClass=!rankReady?'na':r.value>=75?'high':r.value>=50?'mid':'low';
 const pressureMove=diff===null?null:(key==='median'||key==='mean'?-diff:diff),moveClass=pressureMove===null?'':pressureMove>0?'worse':pressureMove<0?'better':'flat',moveLabel=pressureMove===null?'—':pressureMove===0?'持平':`${pressureMove<0?'改善':'加压'} ${Math.abs(diff).toFixed(key==='limit'?0:2)}${key==='limit'?'只':'pp'}`;
 return `<tr><td>${name}${hint?`<small>${hint}</small>`:''}</td><td class="env-current">${key==='median'||key==='mean'?p(v,2):key==='limit'?(valid(v)?v+'只':'—'):ratio(v)}</td><td title="前250日有效 ${r.n}日"><div class="pressure-rank ${rankClass}"><span>${rankReady?r.value.toFixed(1):'样本不足'}</span>${rankReady?`<i><b style="width:${r.value}%"></b></i>`:''}${r.n<200?`<small>有效${r.n}日</small>`:''}</div></td><td><span class="pressure-move ${moveClass}">${moveLabel}</span></td></tr>`
}).join('');
const pressureMore=`<div class="env-trend"><label for="env-pressure-metric">近40日</label><select id="env-pressure-metric">${metrics.map(([n,k])=>`<option value="${k}" ${k===pressureMetric?'selected':''}>${n}</option>`).join('')}</select></div><div id="env-pressure-chart">${chart(rows.slice(-40).map(r=>({date:r.date,v:getters[pressureMetric](r)})),'近40日压力趋势',pressureMetric==='limit')}</div>${limitDownDetails(m)}<p class="env-muted">分位按此前250日计算，不含当日；盘中对比收盘历史仅供参考。pp为百分点。</p>`;
const pressure=card('01 / 市场压力','历史位置',`<div class="env-scroll"><table><thead><tr><th>指标</th><th>当前</th><th>压力分位</th><th>较前日</th></tr></thead><tbody>${pressureRows}</tbody></table></div><p class="env-caption">分位越高，下跌压力越大。</p>${fold('pressure-more','走势与跌停明细',pressureMore)}`);

const promotionTiers=report.promotion_tiers||report.tiers;
const meanOf=values=>{const a=values.filter(valid);return a.length?a.reduce((sum,v)=>sum+v,0)/a.length:null};
const medianOf=values=>{const a=values.filter(valid).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const structureTable=`<div class="env-scroll"><table class="relay-structure-table"><thead><tr><th>晋级阶段</th><th>${liveMode?'封板':'晋级'} / 样本</th><th>晋级率</th><th>断板当天平均收益</th><th>断板 / 样本</th></tr></thead><tbody>${promotionTiers.map(t=>{const failed=t.n-t.promoted,avg=t.failure?.total?.mean??null;return `<tr><td>${t.label||t.height+'板'}</td><td>${t.n?t.promoted+'/'+t.n:'—'}</td><td>${t.n?ratio(t.promoted/t.n):'—'}</td><td class="${tone(avg)}">${p(avg,2)}</td><td>${t.n?failed+'/'+t.n:'—'}</td></tr>`}).join('')}</tbody></table></div>`;
const tracks=(report.tracks||[]).slice().reverse();
const allNextDay=`<div class="env-scroll"><table><thead><tr><th>断板批次</th><th>D+1中位</th><th>D+1上涨占比</th><th>D+1大跌占比</th><th>有效样本</th></tr></thead><tbody>${tracks.map(t=>{const ready=t.d1_ready&&t.d1,positive=ready&&t.d1.n?meanOf(t.items.filter(s=>valid(s.d1)).map(s=>s.d1>0?1:0)):null;return `<tr><td>${t.date.slice(5)}</td><td class="${tone(ready?t.d1.median:null)}">${ready?p(t.d1.median,2):'—'}</td><td>${ready?ratio(positive):'—'}</td><td>${ready?ratio(t.d1.severe):'—'}</td><td>${ready?t.d1.n+'/'+t.n:'—'}</td></tr>`}).join('')}</tbody></table></div>`;
const highTracks=tracks.map(t=>{const items=t.items.filter(s=>s.height>=4);return {...t,items,n:items.length}}).filter(t=>t.n);
const highFeedback=`<div class="env-scroll"><table><thead><tr><th>断板批次</th><th>D+1</th><th>D+2</th><th>D+3</th><th>D+4</th><th>样本</th></tr></thead><tbody>${highTracks.map(t=>{const cell=o=>{const ready=t['d'+o+'_ready'],values=t.items.map(s=>s['d'+o]);const v=ready?medianOf(values):null,n=ready?values.filter(valid).length:0;return `<td class="${tone(v)}" title="${ready?'有效'+n+'/'+t.n+'只':'未到观察日'}">${ready?p(v,2):'—'}</td>`};return `<tr><td>${t.date.slice(5)}</td>${cell(1)}${cell(2)}${cell(3)}${cell(4)}<td>${t.n}只</td></tr>`}).join('')}</tbody></table></div>`;
const feedbackBody=`<h4>全部连板断板股 · 次日反馈</h4>${tracks.length?allNextDay:'<p class="env-muted">暂无已确认断板批次。</p>'}<h4>4板以上断板股 · D+1至D+4</h4>${highTracks.length?highFeedback:'<p class="env-muted">暂无4板以上断板样本。</p>'}`;
const mergedBody=`${structureTable}<p class="env-caption">断板当天平均收益按昨收→当日收盘计算。</p>${fold('failure-section','断板反馈',feedbackBody)}`;
const mergedBad=(valid(relay.intraday.median)&&relay.intraday.median<0)||(valid(failure.total.median)&&failure.total.median<0)||(valid(hf.total.median)&&hf.total.median<0);
q('#env-cards').innerHTML=pressure+card('02 / 接力结构与风险',relay.expected+'只前日连板样本',mergedBody,mergedBad);
q('#env-pressure-metric').onchange=e=>{pressureMetric=e.target.value;render()};
}
async function init(preserve=false){if(refreshBusy)return;refreshBusy=true;try{const chosen=preserve&&db?db.reports[idx].date:null,wasLatest=preserve&&db?chosen===db.asof:true;const r=await fetch('data/environment.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);db=await r.json();idx=!wasLatest&&chosen?db.reports.findIndex(x=>x.date===chosen):db.reports.length-1;if(idx<0)idx=db.reports.length-1;q('#env-date').innerHTML=db.reports.map((r,i)=>`<option value="${i}" ${i===idx?'selected':''}>${r.date}</option>`).join('');q('#env-date').onchange=e=>{idx=Number(e.target.value);render()};render();const statusResponse=await fetch('data/update_status.json?t='+Date.now(),{cache:'no-store'});if(statusResponse.ok){const st=await statusResponse.json();if(st.state==='running')dom.updateTime.textContent='正在更新 · 上次成功 '+(st.last_success||'—').replace('T',' ').slice(0,19);if(st.state==='error')dom.updateTime.textContent='更新失败，保留 '+db.asof+' '+db.quote_time+' · '+st.error;}}catch(e){q('#env-context').textContent='读取失败，保留当前显示：'+e.message}finally{refreshBusy=false}}
dom.reloadBtn.onclick=async()=>{dom.reloadBtn.disabled=true;try{const r=await fetch('/api/update',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const result=await r.json();if(!r.ok)throw Error(result.error||'请求失败');dom.updateTime.textContent='更新已启动，完成后自动显示';}catch(e){dom.updateTime.textContent='无法启动更新：'+e.message}finally{dom.reloadBtn.disabled=false}};
init();setInterval(()=>init(true),30000);

})();
